name: Bug report
description: Report a problem with the umbrella landing or documentation
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting. Please include enough detail to reproduce."
  - type: input
    id: area
    attributes:
      label: Area
      description: Where is the issue?
      placeholder: "README / index.html / GitHub Pages / links"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: "1) ...\n2) ...\n3) ..."
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "OS / Browser / Device"
